name: shell-clone-nodejs
on: [push, workflow_dispatch]
jobs:
  shell-commands:
    runs_on: ubuntu-latest
    steps:
      - name: multiple shell commands
        run: |
            date
            echo "Hello $USER"
            ls -l /root
            cat /etc/passwd
  code-checkout:
    runs_on: ubuntu-latest
    steps:
      - name: pull the repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node_version: '16'