name: run-a-shell-command
on: push
jobs:
  shell-commands-execute:
    runs-on: ubuntu-latest
    steps:
      - name: display date
        run: date
      - name: list current folder
        run: ls -l /
