name: code-checkout
on: push
jobs:
  clone-a-repo:
    runs-on: ubuntu-latest
    steps:
      - name: pull the repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: check where you are
        run: pwd
      - name: list the repo files
        run: ls -al
