name: first-job
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: using env variables
        run: |
            sudo useradd tom
            id tom
            cat /etc/passwd | grep tom
            date
            echo "Hi $USER"
