name: first-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository to local
        uses: actions/checkout@v4

      - name: Welcome Message
        run: echo "Hello Mr Sasi"

      - name: Listing files and floders
        run: ls -ltra