name: first-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository to local
        uses: actions/checkout@v4

      - name: Executing a Shell Script
        run: |
          chmod +x my-script.sh
          ./my-script.sh
      #     echo "Hello Mr Kanth"
      #     ls -ltra
      #     cd .github/workflows
      #     ls -ltr
      # #   run: echo "Hello Mr Sasi"

      # # - name: Listing files and floders
      # #   run: ls -ltra