name: first-workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository to local
        uses: actions/checkout@v4

      - name: Executing a Shell Script
        run: |
          chmod +x my-script.sh
          ./my-script.sh
      - name: creating deploy file
        run: echo "Code Testing & Deploying" > /tmp/code
      - name: Code file content
        run: cat /tmp/code
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test the Application
        run: ls -l /tmp/code
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the Code
        run: echo "Deployingn the code........." && cat /tmp/code