name: first-workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository to local
        uses: actions/checkout@v4

      - name: Executing a Shell Script
        run: |
          chmod +x my-script.sh
          ./my-script.sh
      - name: creating deploy file
        run: echo "Uploading file & Code Testing & Deploying" > /tmp/code
      - name: Code file content
        run: cat /tmp/code
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-file
          path: /tmp/code
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-file
      - name: Test the Application
        run: cat /home/runner/work/actions-practice/actions-practice/code-file
  deploy-job:
    needs: [build-job]
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-file
      - name: Deploy the Code
        run: echo "Deployingn the code........." && cat /home/runner/work/actions-practice/actions-practice/code-file