name: clone-a-repo
on: workflow_dispatch
jobs:
  clone-repository:
    runs-on: ubuntu-latest
    steps:
      - name: clone a repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: install node-js
        uses: actions/setup-node@v3
        with:
          node-version: '16'