name: code-checkout
on: push
jobs:
  install-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: check node version
        run: node -v
      - name: Run Tests
        run: npm test
