name: my-first
on: push
jobs:
  event-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: using gh contexts - github
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: using gh contexts - github.workflow
        run: echo "${{ toJSON(github.workflow) }}"
      - name: display run-id
        run: echo $RUNID
        env:
          RUNID: ${{ toJSON(github.run_id) }}