name: filters example
on:
  push:
    branches:
      - 'develop'
      - 'stage'
jobs:
  push-filter-example:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Repo Locally
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Display repo details 
        run: echo "${{ toJson(github)}}"
