name: filters example
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'stage'
jobs:
  push-filter-example:
    runs-on: ubuntu-latest
    steps:
      - name: Display today's date
        run: date
      - name: Clone the Repo Locally
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '16'
      - name: Display repo details 
        run: echo "${{ toJson(github)}}"
