name: filters example
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  push:
    branches:
      - 'main'    #ee block meaning enti antey, whenever a PR opened and push request to the branches defined here - trigger a workflow ani ardham. Manam develop ane branch lo work chesthaam(like Jira numbers we creare) kaani avi push lo undavu kaabatti workflow trigger avvadu, once aa PR approve iyyaka main ki merge chesthaam kaabatti as per activity type defined here like when a push event comes to main branch trigger the workflow., that is what we are using in our current env.
      - 'stage'
jobs:
  push-filter-example:
    runs-on: ubuntu-latest
    steps:
      - name: Display today's date
        run: date
      - name: Clone the Repo Locally
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Display repo details 
        run: echo "${{ toJson(github) }}"
