name: print-env-variables
on:
  push:
    branches:
      - develop
env:
  DB_NAME: my-test-db
  DB_USER: sasi
  DB_PWD: S@sik@nth123
jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - name: print envs
        run: |
            echo "DB NAME Is: ${{ env.DB_NAME }}"
            echo "DB User Is: ${{ env.DB_USER }}"
            echo $DB_PWD
  read-variables:
    needs: display-variables
    runs-on: ubuntu-latest
    steps:
      - name: Get Vars
        run: echo "Hi $DB_USER"