name: print-env-variables
on:
  push:
    branches:
      - develop
env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PWD: ${{ secrets.DB_PWD }}
jobs:
  read-variables:
    runs-on: ubuntu-latest
    env:
      DB_PORT: 6543
    steps:
      - name: read envs
        run: |
            echo "${{ env.DB_NAME }}"
            echo "${{ env.DB_USER }}"
            echo "${{ env.DB_PWD }}"
            echo "${{ env.DB_PORT }}"
  display-variables:
    runs-on: ubuntu-latest
    needs: read-variables
    env:
      DB_PORT: 6543
    steps:
      - name: print envs
        run: |
            echo $DB_NAME
            echo $DB_USER
            echo $DB_PWD
            echo "${{ env.DB_PORT }}"
            echo "${{ env.DB_PORT }}"