name: all-in-one-practice
on: [workflow_dispatch]
jobs:
  display-values:
    runs-on: ubuntu-latest
    steps:
      - name: Display Values with echo
        run: echo "Hello $USER"
      - name: Run Shell Commands
        run: ls -l /etc
      - name: run multiple commands
        run: |
          echo "Hello World"
          ls -l /tmp
          mkdir /tmp/test
          touch /tmp/test/data
  build-job:
    needs: display-values
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: confirmation
        run: echo "Workflow is: $GITHUB_REPOSITORY"