name: code-checkout
on: workflow_dispatch
jobs:
  clone-a-repo:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo from github
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: check where are you now
        run: pwd
      - name: list the repo folder
        run: ls -la
  install-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
