name: code checkout
on: push
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from git
        uses: actions/checkout@v3
      - name: find your location
        run: pwd
      - name: list your repo
        run: ls -al
