name: code checkout
on: push
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: pull the code from github
        uses: actions/checkout@v3
      - name: where you are
        run: pwd
      - name: contents in repo
        run: ls -la
