name: on-push-example
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  pull-the-code
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.6.0
      - name: list project folder
        run: |
          ls -la
          date
          pwd
