name: on-push-example
on: workflow_dispatch
jobs:
  pull-the-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.6.0
      - name: list the folder
        run: |
          ls -la
          pwd
          date
