name: first-workflow
on: workflow_dispatch
jobs:
  display-content:
    runs-on: ubuntu-latest
    steps:
      - name: display date
        run: date
      - name: print message
        run: echo "Hi $USER"
  create-user:
    runs-on: ubuntu-latest
    steps:
      - name: create user
        run: sudo useradd tom
      - name: print message
        run: echo "Hi $USER"  
