name: practice-workflow
on: workflow_dispatch
env:
  DB_PORT: 5432
jobs:
  global-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Store env vars
        run: echo "MY_NAMES=Local" >> $GITHUB_ENV
      - name: Display Environment Variable
        run: echo "${{ env.MY_NAME }}"
