name: env-vars
on: [workflow_dispatch, push]
env:
  USER: sasi
jobs:
  display_global_vars:
    runs-on: ubuntu-latest
    steps:
      - name: display date
        run: |
            date
            ls -l
            who
      - name: env vars display
        run: echo "${{ env.USER }}"
  display_local_vars:
    needs: display_global_vars
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Akula
      LAST_NAME: Kanth
    steps:
      - name: display local vars
        run: |
            echo "${{ env.FIRST_NAME }}"
            echo "${{ env.LAST_NAME }}"
            echo "Hi ${{ env.USER}}"
  display_local_vars:
    needs: display_local_vars
    runs-on: ubuntu-latest
    steps:
      - name: display local vars fron different jobs
        run: |
            echo "${{ env.FIRST_NAME }}"
            echo "${{ env.LAST_NAME }}"
            echo "Hi ${{ env.USER}}"