name: env-variables
on: workflow_dispatch
env:
  USER: sasi
jobs:
  display_vars:
    runs-on: ubuntu-latest
    steps:
      - name: display date
        run: |
            date
            ls -l
            who
      - name: env vars display
        run: echo "${{ env.USER }}"
  greetings:
  env:
    first_name: akula
    last_name: kanth
    needs: display_vars
    runs-on: ubuntu-latest
    steps:
      - name: local env vars
        run: |
          echo "{{ env.first_name }}"
          echo "{{ env.last_name }}"