name: my-first
on: workflow_dispatch
jobs:
  event-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: using gh contexts - github
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: using gh contexts - github.workflow
        run: echo "${{ toJSON(github.workflow) }}"
      - name: display run-id
        run: echo $RUNID
        env:
          RUNID: ${{ toJSON(github.run_id) }}

          #<<<<<<< develop
      - 'main'    #ee block meaning enti antey, whenever a PR opened and push request to the branches defined here - trigger a workflow ani ardham. Manam develop ane branch lo work chesthaam(like Jira numbers we creare) kaani avi push lo undavu kaabatti workflow trigger avvadu, once aa PR approve iyyaka main ki merge chesthaam kaabatti as per activity type defined here like when a push event comes to main branch trigger the workflow., that is what we are using in our current env.
=======
      - 'main'