name: practice-workflow
on: workflow_dispatch
env:
  MY_NAME: Sasi
jobs:
  global-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Store env vars
        run: echo "MY_NAME=Local" >> $GITHUB_ENV
    steps:
      - name: Display Environment Variable
        run: echo "${{ env.MY_NAME }}"
