name: env_variables
on: [push, workflow_dispatch]
env:
  user: sasi
jobs:
  display_vars:
    runs_on: ubuntu-latest
    steps:
      - name: display date
        run: |
          date
          ls -l
          who
      - name: env vars display
        run: echo "Hi $user"